### ISSUE TITLE
writeProperty: property/invalid-data-type

### ISSUE THREAD

**Issue by goliatone** [relayr/node-bacnet#13]
I am able to use `readProperty` to get a value from an object. I am trying to `writeProperty` and I keep getting an **error-ack*:

```
Error in callback Error: Error received in acknowledgment for request #1 property/invalid-data-type
    at BACnetInstance.onErrorAck (/node_modules/bacnet/bacnet.js:85:36)
    at emitTwo (events.js:106:13)
    at BACnetInstance.emit (events.js:191:7)
```

The way I'm calling the function:

```js
client.writeProperty('198.80.70.30', 'analog-value', 18957, 'present-value', false, 75, next);
```

I've also tried to build the value using `bacnet.BacnetValue`:
```js
let value = new bacnet.BacnetValue(73, tag);
```
But I'm not sure what value to assign to `tag`. I have tried of the following numeric values:
* 2 (unsigned int)
* 3 (signed int)
* 4 (real)
* 5 (double)

Any pointers wold be much appreciated.

**Comment by goliatone** [comment]
Found the mistake. The tag value should be a string. In this particular case, it should have been "Real".
```js
let value = new bacnet.BacnetValue(73, 'Real');
```

**Comment by platy** [comment]
I'm glad you found it, using BacnetValue is the only way to produce a real value once its converted to Bacnet, and as Bacnet is (as far as i have seen) strongly typed, this is how we have to do it.

The other type tags are in [bactext.c](https://github.com/relayr/node-bacnet/blob/master/bacnet-stack/src/bactext.c#L123), which has string representations for all of the enums, some of which are used in the JS wrapper.
