### ISSUE TITLE
on readProperty.js example "Present_Value" is not recognized as a valid property key

### ISSUE THREAD

**Issue by 16alexanders** [relayr/node-bacnet#14]
`node readProperty.js 4194303  device 90020  present_value 41`

                              
I've tried:

```
present_value
Present_Value
"present_value"
"Present_Value"
```

**Comment by platy** [comment]
Try "present-value", also the enum strings are in the bactext.c source file: https://github.com/relayr/node-bacnet/blob/master/bacnet-stack/src/bactext.c

**Comment by 16alexanders** [comment]
Fixed it, I was just trying to read the wrong thing needed to use multi-state-value as the Object type
