### ISSUE TITLE
Where do I disable PRINT_ENABLED?

### ISSUE THREAD

**Issue by 16alexanders** [relayr/node-bacnet#15]
I'm trying to modify the readProperty.js example specific to my use case... it prints out a lot of extraneous information that I don't need. Instead of calling the file readProperty.js with arguments I'd like to make readPresentValue(.....) a function on its own. All I want to log is  `property.value`. Can anyone offer assistance?

I see PRINT_ENABLED often in the C code but not sure where I can disable it globally?

**Comment by platy** [comment]
PRINT_ENABLED is set as part of the build definition in binding.gyp, if you change it in there and do a rebuild that should have the desired effect

**Comment by 16alexanders** [comment]
Ok, I set the PRINT_ENABLED to 0 in binding.gyp and did an `npm rebuild` but didn't have the intended effect. Still getting "Received I-Am Request.... "

**Comment by 16alexanders** [comment]
Ok that worked... I just ran rebuild again... thanks for you help. I'm using your code to send commands to BACNET devices using voice commands. See the Snowboy hotword recognition library and Sonus library.
