### ISSUE TITLE
How to build and use this bacnet node in Linux ?

### ISSUE THREAD

**Issue by titusece** [relayr/node-bacnet#7]
Hi,
Can you please tell how to build this node js and use it ?
I have BACnet client (Bacnet discovery tool) to communicate with this bacnet node.
Thanks.

I have got an error like this..

I have downloaded "'node-v4.4.7.tar.gz" source and build and to updated node.

titus@titus-laptop:~/Downloads/node-bacnet-master$ 
titus@titus-laptop:~/Downloads/node-bacnet-master$ node-gyp clean
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.10
gyp info using node@0.10.25 | linux | ia32
gyp info ok 
titus@titus-laptop:~/Downloads/node-bacnet-master$ 
titus@titus-laptop:~/Downloads/node-bacnet-master$ 
titus@titus-laptop:~/Downloads/node-bacnet-master$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.10
gyp info using node@0.10.25 | linux | ia32
gyp info spawn python
gyp info spawn args [ '/usr/share/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/titus/Downloads/node-bacnet-master/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dmodule_root_dir=/home/titus/Downloads/node-bacnet-master',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/titus/Downloads/node-bacnet-master/build'
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/apdu.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/npdu.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bacdcode.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bacint.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bacreal.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bacstr.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bacapp.o
../bacnet-stack/src/bacapp.c: In function ‘append_str’:
../bacnet-stack/src/bacapp.c:1021:5: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     if ((bytes_written < 0) || (bytes_written >= *rem_str_len)) {
     ^
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bacprop.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bactext.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bip.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bvlc.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/datetime.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/indtext.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/key.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/keylist.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/proplist.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/debug.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bigend.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/arf.o
../bacnet-stack/src/arf.c: In function ‘arf_ack_decode_service_request’:
../bacnet-stack/src/arf.c:299:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (decoded_len != len_value_type) {
                             ^
../bacnet-stack/src/arf.c:346:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (decoded_len != len_value_type) {
                                 ^
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/awf.o
../bacnet-stack/src/awf.c: In function ‘awf_decode_service_request’:
../bacnet-stack/src/awf.c:142:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (decoded_len != len_value_type) {
                             ^
../bacnet-stack/src/awf.c:184:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (decoded_len != len_value_type) {
                                 ^
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/cov.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/dcc.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/iam.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/ihave.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/rd.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/rp.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/rpm.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/timesync.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/whohas.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/whois.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/wp.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/wpm.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/abort.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/reject.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bacerror.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/ptransfer.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/memcopy.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/filename.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bacaddr.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/address.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bacdevobjpropref.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/bacpropstates.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/alarm_ack.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/event.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/getevent.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/get_alarm_sum.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/readrange.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/timestamp.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/lighting.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/src/version.o
  CC(target) Release/obj.target/bacnet_stack/bacnet-stack/ports/linux/bip-init.o
../bacnet-stack/ports/linux/bip-init.c: In function ‘get_local_address_ioctl’:
../bacnet-stack/ports/linux/bip-init.c:86:12: warning: missing initializer for field ‘ifr_ifru’ of ‘struct ifreq’ [-Wmissing-field-initializers]
     struct ifreq ifr = { {{0}} };
            ^
In file included from ../bacnet-stack/ports/linux/net.h:81:0,
                 from ../bacnet-stack/include/bip.h:32,
                 from ../bacnet-stack/ports/linux/bip-init.c:38:
/usr/include/net/if.h:149:9: note: ‘ifr_ifru’ declared here
       } ifr_ifru;
         ^
  AR(target) Release/obj.target/bacnet_stack.a
  COPY Release/bacnet_stack.a
  CXX(target) Release/obj.target/binding/src/module.o
../src/module.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE InitInstance(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/module.cc:39:167: warning: narrowing conversion of ‘bbmd_port’ from ‘uint32_t {aka unsigned int}’ to ‘long int’ inside { } [-Wnarrowing]
     struct BACNET_CONFIGURATION config = {device_instance_id, ip_port, apdu_timeout, apdu_retries, iface.c_str(), invoke_id, bbmd_port, bbmd_ttl, bbmd_address.c_str()};
                                                                                                                                                                       ^
../src/module.cc:39:167: warning: narrowing conversion of ‘bbmd_ttl’ from ‘uint32_t {aka unsigned int}’ to ‘long int’ inside { } [-Wnarrowing]
../src/module.cc: In function ‘void InitModule(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
_../src/module.cc:79:29: error: no matching function for call to ‘BacnetValue::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE&)’
     BacnetValue::Init(target);_
                             ^
../src/module.cc:79:29: note: candidate is:
In file included from ../src/module.cc:4:0:
../src/BacnetValue.h:14:15: note: static void BacnetValue::Init(v8::Local<v8::Object>)
   static void Init(Local<Object> exports);
               ^
../src/BacnetValue.h:14:15: note:   no known conversion for argument 1 from ‘Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE {aka v8::Handle<v8::Object>}’ to ‘v8::Local<v8::Object>’
make: *** [Release/obj.target/binding/src/module.o] Error 1
make: Leaving directory `/home/titus/Downloads/node-bacnet-master/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/titus/Downloads/node-bacnet-master
**gyp ERR! node -v v0.10.25**
**gyp ERR! node-gyp -v v0.10.10**
gyp ERR! not ok 
titus@titus-laptop:~/Downloads/node-bacnet-master$ 
titus@titus-laptop:~/Downloads/node-bacnet-master$ 
titus@titus-laptop:~/Downloads/node-bacnet-master$ node -v
**v4.4.7**
titus@titus-laptop:~/Downloads/node-bacnet-master$ 
titus@titus-laptop:~/Downloads/node-bacnet-master$ 
titus@titus-laptop:~/Downloads/node-bacnet-master$ nodejs -v
**v0.10.25**
titus@titus-laptop:~/Downloads/node-bacnet-master$ 
titus@titus-laptop:~/Downloads/node-bacnet-master$ npm -v
**2.15.8**
titus@titus-laptop:~/Downloads/node-bacnet-master$ 
titus@titus-laptop:~/Downloads/node-bacnet-master$ 

Regards,
Titus S.

**Comment by platy** [comment]
Hi Titus,

the node-gyp version you are using is 0.10 - which I understand will build against the node engine for version 0.10.

The recommended method to build is to use `npm install` - it's not very clear in the documentation - npm includes node-gyp and since your npm version seems to be recent that will probably work.

I also recommend [nvm](https://github.com/creationix/nvm) for installing and managing versions of nodejs.

**Comment by titusece** [comment]
Thanks....
I can run discover and test.js files but how can I do it read and write property...
Can you please tell me what is the command for that ?
Ex:
node readProperty.js <>

**Comment by platy** [comment]
try:

    node readProperty.js <deviceInstance> <objectType> <objectInstance> <property> <arrayIndex>

where:
deviceInstance: ip address or device instance number
objectType: object type number or name from https://github.com/relayr/node-bacnet/blob/4a4de5dc98fb65d144b14d479be0a236734c85d1/bacnet-stack/src/bactext.c#L175
objectInstance: object instance number
property: property number or name from https://github.com/relayr/node-bacnet/blob/4a4de5dc98fb65d144b14d479be0a236734c85d1/bacnet-stack/src/bactext.c#L306

write is the same but has an extra value field at the end.

**Comment by titusece** [comment]
Thank you so much.
